# PyTorch

PyTorch is a deep learning framework from Facebook. It's a bit hard to use, but we'll go through the concepts here.

In [1]:
import torch

PyTorch uses a data type called Tensors, which are similar to numpy arrays, except that PyTorch can do fancy mathematical operations on them, and keep track of automatic differentiation.

In [2]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


These objects can be moved to a computer's GPU to allow for faster parallel processing. This is very useful for training. Not every computer has a GPU though.

In [3]:
if torch.cuda.is_available():
    b.cuda()

If you set a Tensor's .requires_grad attribute to True, it will start tracking all operations done to it, for automatic differentiation. After performing calculations with the Tensor, you can call .backward() to compute all derivatives, which are stored in the .grad attribute.

In [44]:
x = torch.Tensor([3])
x.requires_grad = True

In [41]:
y = 5*x + 3
print(y)
y.backward()
print(x.grad)

tensor([ 18.])
tensor([ 5.])


If you want to calculate a variable's gradient again, you have to clear all the gradient history that's been built up with the following command. Else you'll get the wrong gradient values (they accumulate each time you call .backward()).

In [58]:
x.grad.data.zero_()

tensor([ 0.])

In [59]:
y = 5*x**3
print(y)
y.backward()
print(x.grad)

tensor([ 135.])
tensor([ 135.])


## PyTorch Neural Net

Here's how you build a neural net in PyTorch. You have to create a class inheriting from torch.nn.Module. This class needs a function \_\_init\_\_() that sets up the net, and a function forward() that defines what happens during a forward pass through the net.

In [66]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
